import React, { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Device from "app/components/Device";
import ListItem from "app/components/DeviceListWrapper";
import ListOpenButton from "app/components/ListOpenButton";
import ChangeScheduleModal from "app/components/ChangeScheduleModal";
import PageTitle from "app/components/PageTitle";

const Schedule: NextPage = () => {
  const [openModal, setOpenModal] = useState<boolean>(false);

  return (
    <>
      <Head>
        <title>Blinder - Smart blind automation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTitle>Schedule</PageTitle>
      <ListItem>
        <Device
          key="livingroom"
          label="Turn off devices"
          subLabel={
            <>
              <span className="uppercase">Last Run: </span>
              <span>Just Now</span>{" "}
            </>
          }
          action={
            <ListOpenButton
              onClick={() => {
                setOpenModal(true);
              }}
            />
          }
        />
      </ListItem>
      <ChangeScheduleModal
        openModal={openModal}
        onClose={() => setOpenModal(false)}
      />
    </>
  );
};

export default Schedule;
