import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { SignUp } from "@clerk/nextjs";
import AuthErrorBoundary from "app/components/AuthErrorBoundary";

const RegisterPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Blinder - Smart blind automation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthErrorBoundary>
        <SignUp />
      </AuthErrorBoundary>
    </>
  );
};

export default RegisterPage;
