import type { NextPage } from "next";
import Head from "next/head";
import Device from "app/components/Device";
import DeviceListWrapper from "app/components/DeviceListWrapper";
import Toggle from "app/components/Toggle";
import PageTitle from "app/components/PageTitle";

const DevicePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Blinder - Smart blind automation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTitle>Devices</PageTitle>
      <DeviceListWrapper>
        <Device
          key="livingroom"
          label="Living Room"
          action={
            <Toggle
              id=""
              state
              onChange={() => {
                console.log("vv");
              }}
            />
          }
        />
      </DeviceListWrapper>
      <DeviceListWrapper>
        <Device
          key="bedroom"
          label="Bedroom"
          action={
            <Toggle
              id=""
              state
              onChange={() => {
                console.log("vv");
              }}
            />
          }
        />
      </DeviceListWrapper>
    </>
  );
};

export default DevicePage;
