import type { NextPage } from "next";
import Head from "next/head";
import Device from "app/components/Device";
import ListItem from "app/components/ListItem";
import ListOpenIcon from "app/components/ListOpenIcon";
import DeviceGroupModal from "app/components/DeviceGroupModal";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Blinder - Smart blind automation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mb-8 text-4xl md:text-6xl font-bold leading-tight tracking-tighter text-neutral-800">
        Groups
      </div>
      <ListItem>
        <Device key="livingroom" label="Upstairs" action={<ListOpenIcon />} />
      </ListItem>
      <ListItem>
        <Device key="bedroom" label="Downstairs" action={<ListOpenIcon />} />
      </ListItem>
      <DeviceGroupModal isOpen={false} />
    </>
  );
};

export default Home;
