import React, { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Device from "app/components/Device";
import ListItem from "app/components/DeviceListWrapper";
import ListOpenButton from "app/components/ListOpenButton";
import DeviceGroupModal from "app/components/DeviceGroupModal";
import PageTitle from "app/components/PageTitle";

const Group: NextPage = () => {
  const [openModal, setOpenModal] = useState<boolean>(false);

  return (
    <>
      <Head>
        <title>Blinder - Smart blind automation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTitle>Groups</PageTitle>
      <ListItem>
        <Device
          key="livingroom"
          label="Upstairs"
          action={
            <ListOpenButton
              onClick={() => {
                setOpenModal(true);
              }}
            />
          }
        />
      </ListItem>
      <ListItem>
        <Device
          key="bedroom"
          label="Downstairs"
          action={
            <ListOpenButton
              onClick={() => {
                setOpenModal(true);
              }}
            />
          }
        />
      </ListItem>
      <DeviceGroupModal
        openModal={openModal}
        onClose={() => {
          setOpenModal(false);
        }}
      />
    </>
  );
};

export default Group;
