import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Device from "app/components/Device";
import ListItem from "app/components/ListItem";
import ListOpenButton from "app/components/ListOpenButton";
import DeviceGroupModal from "app/components/DeviceGroupModal";

const Home: NextPage = () => {
  const [openModal, setOpenModal] = useState<boolean>(false);

  return (
    <>
      <Head>
        <title>Blinder - Smart blind automation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mb-8 text-4xl md:text-6xl font-bold leading-tight tracking-tighter text-neutral-800">
        Groups
      </div>
      <ListItem>
        <Device
          key="livingroom"
          label="Upstairs"
          action={
            <ListOpenButton
              onClick={() => {
                setOpenModal(true);
              }}
            />
          }
        />
      </ListItem>
      <ListItem>
        <Device
          key="bedroom"
          label="Downstairs"
          action={
            <ListOpenButton
              onClick={() => {
                setOpenModal(true);
              }}
            />
          }
        />
      </ListItem>
      <DeviceGroupModal
        isOpen={openModal}
        onClose={() => setOpenModal(false)}
        onSave={() => setOpenModal(false)}
      />
    </>
  );
};

export default Home;
