import type { NextPage } from "next";
import Head from "next/head";
import Device from "app/components/device";
import DeviceListWrapper from "app/components/deviceListWrapper";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Blinder - Smart blind automation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mb-8 text-4xl md:text-6xl font-bold leading-tight tracking-tighter text-neutral-800">
        Devices
      </div>
      <DeviceListWrapper>
        <Device key="livingroom" label="Living Room" state={false} />
      </DeviceListWrapper>
      <DeviceListWrapper>
        <Device key="bedroom" label="Bedroom" state={true} />
      </DeviceListWrapper>
    </>
  );
};

export default Home;
