version: '3.1'

services:

  mongo:
    container_name: smart-blind-mongo
    image: mongo:5.0.9
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: smart
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo:/data/db

volumes:
  mongo:
