name: Node.js CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Read package.json
        uses: dutscher/read-package-json-endpoint-actions@v1.33.7
        id: package-json-endpoint

      - name: Show version number
        run: echo "${{ steps.package-json-endpoint.outputs.endpoint }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./packages/hub
          platforms: linux/amd64,linux/arm64
          push: true
          tags: smart-blinds/hub:${{ steps.package-json-endpoint.outputs.endpoint }}
