name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install -g yarn
      - run: yarn
      - name: Bootstrap
        run: npx oao bootstrap
      - name: Build
        run: cd packages/hub && yarn build
